### PR TITLE
rename readme.md

### PR DESCRIPTION
**Pull request by hardworking-programmer**

### CODE REVIEW

**Comment by gazalthecoder** [comment]
Thankyou For Countirbuting to my project.

**Comment by gazalthecoder** [comment]
Can you please help me to updated readme too.

**Comment by hardworking-programmer** [comment]
of course my love. 
Please learn Markdwon Language syntax. So we can discuss next step.

**Comment by gazalthecoder** [comment]
Okay.
we will discuss this tomorrow.
Have a nice day.

**Pull request merged**
